### ISSUE TITLE
SCRIPT438: Object doesn't support property or method 'init'  in IE8

### ISSUE THREAD

**Issue by Rajasreem** [johnnyfreeman/placeholder#3]
Hi, 
 I am getting this "SCRIPT438: Object doesn't support property or method 'init" error in IE8 while using jquery.jcrop.min.js for image cropping.

Is there any work around for this??

**Comment by johnnyfreeman** [comment]
Hey there.

Didn't realize anyone was (still) using this placeholder plugin. I haven't updated it in years. Anyways, it sounds like the error has to do with the jcrop plugin. Or is there some reason you think it's due to the placeholder plugin?

**Comment by Rajasreem** [comment]
Hi,

This issue is not due to the placeholder plugin. I think the problem with the Jcrop plugin.

Thanks.
